### ISSUE TITLE
Check whether `yarn` is a requirement for Zendro

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/zendro#17]
It seems that we need `yarn`. 

Please check. If it is required, have the CLI generate an error message if it is not present.

Add documentation of this requirement.

**Comment by qwerdenkerXD** [comment]
The `start` command also uses `yarn`.
`yarn build`, `yarn dev` and `yarn start`

**Comment by qwerdenkerXD** [comment]
I tried to get around this issue by adding yarn to zendro's package.json
Then I changed all calls of `yarn` to calls of `npm exec -- yarn`
Works fine, I can create projects, run them without docker, but when running with docker in SPA login occurs the error:

>(api)/src/pages/api/auth/[...nextauth].ts (15:8) @ eval
>
 > 13 | 
   14 | if (!OAUTH2_TOKEN_URI || !OAUTH2_CLIENT_ID || !OAUTH2_CLIENT_SECRET) {
   15 | throw new Error(
        |      ^
  16 |   'Some mandatory OAuth2 variables in your `.env` are not being set'
  17 | );
  18 | }

Should be set in keycloak migration

**Comment by qwerdenkerXD** [comment]
Found the problem. this happened because I hat docker images with same repository name, which were created in a project with the same name.
I reset my projects by just deleting their folders. When I now recreate the projects, the keycloak migration fails because it is already set up and can't set duplicate Users and stuff. This is why the SPA credentials can't be set and so I run into the error.
